### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by feddamisch** [feddamisch/iris-desktop#1]
- [ ] Create a common plugin interface for all the parts of Iris (`libiris-core-plugin`)
- [ ] Implement components that both implement and provides a subclass of `libiris-plugin` (i.e. Iris Panel would both implement `IrisCorePlugin` and provide `IrisPanelPlugin`), so we can have individual plugins on component plugins (applets in the case of Panel).
- [ ] Implement a common plugin loader (`iris-core-loader`, `iris-loader` or just `iris-session`/`iris-desktop`?) that will load all the core components (asyncly, if possible) as provided by the `org.iris-desktop.[core|session] components` setting.
- [ ] Find a way to communicate with plugins using DBus or another RPC mechanism.
- [ ] Make sure every Component has an accesible plugin management interface (Peas PluginManager but looking better!).
- [ ] Make sure we almost never touch /usr/bin (or whatever), put stuff on `/usr/libexec` and call them from `iris-core` if possible.

**Comment by feddamisch** [comment]
Note: `iris-session` will be the main session thing, that will execute `iris-shell` and shit will appear on screen (maybe).

**Comment by feddamisch** [comment]
Also, we need to decide for Vala or C or C++, Vala looks like the best option because it's GNOME's own language and integrates pretty well with all the signal and DBus and other stuffs

**Comment by feddamisch** [comment]
Aaaand... Everything will be Qt!
